#
# Copyright (c) 2015 by Delphix. All rights reserved.
#
---
#
# Add "registry.yourdomain.local" to "/etc/hosts" so that we can use the
# hostname of our nginx server block (vhost) which serves the private Docker
# registry. The IP address of "registry.yourdomain.local" will be the IP of
# "eth0".
#
- hosts: all
  become: yes
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
